modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Vazkii/Psi"

[[mods]]
modId="quark"
displayName="Quark"
version="${version}"
authors="Vazkii, Wiiv, WireSegal, MCVinnyq"
description='''
Small things.
'''
